package beans;
// Generated May 20, 2013 1:35:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CommunityMsg generated by hbm2java
 */
public class CommunityMsg  implements java.io.Serializable {


     private Integer commMsgId;
     private String msgTitle;
     private String msgDescription;
     private Date reportingTime;
     private String latlong;
     private String msgType;
     private Date expiryTime;

    public CommunityMsg() {
    }

	
    public CommunityMsg(Date reportingTime, Date expiryTime) {
        this.reportingTime = reportingTime;
        this.expiryTime = expiryTime;
    }
    public CommunityMsg(String msgTitle, String msgDescription, Date reportingTime, String latlong, String msgType, Date expiryTime) {
       this.msgTitle = msgTitle;
       this.msgDescription = msgDescription;
       this.reportingTime = reportingTime;
       this.latlong = latlong;
       this.msgType = msgType;
       this.expiryTime = expiryTime;
    }
   
    public Integer getCommMsgId() {
        return this.commMsgId;
    }
    
    public void setCommMsgId(Integer commMsgId) {
        this.commMsgId = commMsgId;
    }
    public String getMsgTitle() {
        return this.msgTitle;
    }
    
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle;
    }
    public String getMsgDescription() {
        return this.msgDescription;
    }
    
    public void setMsgDescription(String msgDescription) {
        this.msgDescription = msgDescription;
    }
    public Date getReportingTime() {
        return this.reportingTime;
    }
    
    public void setReportingTime(Date reportingTime) {
        this.reportingTime = reportingTime;
    }
    public String getLatlong() {
        return this.latlong;
    }
    
    public void setLatlong(String latlong) {
        this.latlong = latlong;
    }
    public String getMsgType() {
        return this.msgType;
    }
    
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }
    public Date getExpiryTime() {
        return this.expiryTime;
    }
    
    public void setExpiryTime(Date expiryTime) {
        this.expiryTime = expiryTime;
    }




}


