package beans;
// Generated May 20, 2013 1:35:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Devices generated by hbm2java
 */
public class Devices  implements java.io.Serializable {


     private String regId;
     private String email;

    public Devices() {
    }

	
    public Devices(String regId) {
        this.regId = regId;
    }
    public Devices(String regId, String email) {
       this.regId = regId;
       this.email = email;
    }
   
    public String getRegId() {
        return this.regId;
    }
    
    public void setRegId(String regId) {
        this.regId = regId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


