package beans;
// Generated May 20, 2013 1:35:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String username;
     private String pswd;

    public Users() {
    }

	
    public Users(String username) {
        this.username = username;
    }
    public Users(String username, String pswd) {
       this.username = username;
       this.pswd = pswd;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPswd() {
        return this.pswd;
    }
    
    public void setPswd(String pswd) {
        this.pswd = pswd;
    }




}


